version: '3.8'

services:
  hub:
    image: ${DOCKER_IMAGE:-ghcr.io/namp88/hoosat-dev-hub:latest}
    container_name: hoosat-dev-hub-prod
    ports:
      - "127.0.0.1:3003:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge
