import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Hoosat Hub Documentation Sidebars
 *
 * Organized by sections:
 * - Getting Started: Introduction and quick start guides
 * - SDKs: Language-specific SDK documentation (Node.js, Browser)
 * - REST API: Public HTTP API documentation
 * - Wallet Extension: Browser extension wallet for Hoosat
 */
const sidebars: SidebarsConfig = {
  // Getting Started sidebar
  gettingStartedSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'intro',
        'quick-start',
      ],
    },
  ],

  // Node.js SDK sidebar (hoosat-sdk)
  sdkJsSidebar: [
    {
      type: 'category',
      label: 'Node.js SDK',
      items: [
        {type: 'autogenerated', dirName: 'sdk-js'},
      ],
    },
  ],

  // Browser SDK sidebar (hoosat-sdk-web)
  sdkWebSidebar: [
    {
      type: 'category',
      label: 'Browser SDK',
      items: [
        {type: 'autogenerated', dirName: 'sdk-web'},
      ],
    },
  ],

  // REST API sidebar (hoosat-proxy)
  restApiSidebar: [
    {
      type: 'category',
      label: 'REST API',
      items: [
        {type: 'autogenerated', dirName: 'rest-api'},
      ],
    },
  ],

  // Wallet Extension sidebar (hoosat-web-extension)
  walletExtensionSidebar: [
    {
      type: 'category',
      label: 'Wallet Extension',
      items: [
        {type: 'autogenerated', dirName: 'wallet-extension'},
      ],
    },
  ],
};

export default sidebars;
